### ISSUE TITLE
Make contract address only dependent on the user's account address and salt.

### ISSUE THREAD

**Issue by Georgi87** [gnosis/contract-proxy-kit#12]
Currently, the proxy address is dependent on the `deploymentData`, which is defined by the Dapp. `deploymentData` might vary dependent on the user interaction, which would lead to creation of different proxies for the same Dapp. This created unnecessary friction. A solution to this issue would be to make the proxy address only dependent on the user's address and the salt. A Dapp, which specifically wants to have different proxy accounts can still create those by changing the salt.

**Comment by rmeissner** [comment]
This should already be the case for the current CPK factory (https://github.com/gnosis/contract-proxy-kit/blob/master/contracts/CPKFactory.sol).

**Comment by cag** [comment]
Yup, the initial transaction should not affect the generated proxy address; that's precisely why `create` doesn't ask for data from the first transaction. That said, one of the pieces of input data for the proxy is the creationCode for the Proxy, which depends on its Solidity code and the compiler used to compile it. I currently ask for it from the factory via (https://github.com/gnosis/contract-proxy-kit/blob/c17906d4df64ba3ae8703fbaf2bd5d627dc3083c/contracts/CPKFactory.sol#L10), which is why `create` is asynchronous.

**Comment by Georgi87** [comment]
What was the reasoning to include the creationCode and the masterCopy in the creation process?

**Comment by rmeissner** [comment]
This is required by create2 (and create actually). This is just building the deployment code

**Comment by Georgi87** [comment]
nvm, all good. thank you!
