### ISSUE TITLE
Sending a transaccion using WalletConnect through the safe app returns a never fulfulling promise

### ISSUE THREAD

**Issue by photonite** [gnosis/contract-proxy-kit#137]
Transactions sent by WalletConnect never return a receipt. They return a pending promise that never fulfills no matter if the safe owner(s) confirm or reject the transaction.

Code example: 
```typescript
import WalletConnectProvider from '@walletconnect/web3-provider'

const provider = new WalletConnectProvider({
   infuraId: '...',
})

provider.enable().then(async () => {

   const tx = {
      from: '0x...',
      to: '0x....',
      value: '1'
   }

   const receipt = await provider.wc.sendTransaction(tx)

   console.log(receipt) // never reached
})

```

**Comment by rmeissner** [comment]
I am not sure if this issue is related to the CPK. It seems this is more a issue of the https://github.com/gnosis/safe-react-apps/tree/development/apps/tx-builder and is related to https://github.com/gnosis/safe-react-apps/issues/62 

If this is not the case please provide more information (e.g. How did you connect with wallet connect? Is there an example app? what Safe related sdks did you use and what version?)

**Comment by photonite** [comment]
@rmeissner 
Thanks for referring me to the relevant issues, I'll take a look at them. here's an example repo [mm-wallet-connect-prototype](https://github.com/photonite/mm-wallet-connect-prototype), however, it uses no safe specific library or sdk, as it is supposed to connect to the safe app by using the QR code.
