### ISSUE TITLE
GAS relayer support 

### ISSUE THREAD

**Issue by Graeme-Code** [gnosis/contract-proxy-kit#19]
Hi, 

This ticket will not be super in-depth but more posing a question. One of the largest usability issues in ethereum for people who have not used a Dapp before is GAS. Would it be possible for the CPK to facilitate transactions on behalf of the user and covers their GAS costs?

**Comment by cag** [comment]
Hey Graeme,

I think this is related to #13 

Anyway, currently, not easily. There's not official functionality offered by this kit, but in principle it's possible. Basically, users would have to sign a transaction executable by `execTransactions` off of the predetermined Safe, and then pass this signed transaction to a generous relayer.

I'll keep this open in order to allow this use case to be further expanded if that is desirable, but currently, there are no plans to implement this.

**Comment by pimato** [comment]
@cag we would love to see this feature beeing added as it gives all other clients like metamask and even hardware wallets all those nice features the gnosis safe is currently providing. Some people just don`t want to move all their funds into a mobile native smart wallet right now.
